-- ============================================================================
-- 20_data_retention.sql -- bounded operational-data retention
-- ============================================================================
-- Financial and user-facing history is deliberately excluded. This migration
-- only removes expired security records and old operational/audit data.
-- Supabase Cron runs inside Postgres, so cleanup is reliable even while the
-- Render web service is asleep.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pg_cron;

CREATE TABLE IF NOT EXISTS data_retention_settings (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  sync_jobs_done_days INTEGER NOT NULL DEFAULT 90 CHECK (sync_jobs_done_days >= 30),
  sync_jobs_failed_days INTEGER NOT NULL DEFAULT 180 CHECK (sync_jobs_failed_days >= 30),
  read_notifications_days INTEGER NOT NULL DEFAULT 90 CHECK (read_notifications_days >= 30),
  unread_notifications_days INTEGER NOT NULL DEFAULT 365 CHECK (unread_notifications_days >= 90),
  system_logs_days INTEGER NOT NULL DEFAULT 30 CHECK (system_logs_days >= 7),
  error_logs_days INTEGER NOT NULL DEFAULT 90 CHECK (error_logs_days >= 30),
  admin_audit_days INTEGER NOT NULL DEFAULT 365 CHECK (admin_audit_days >= 180),
  shopping_invitations_days INTEGER NOT NULL DEFAULT 180 CHECK (shopping_invitations_days >= 30),
  revoked_devices_days INTEGER NOT NULL DEFAULT 180 CHECK (revoked_devices_days >= 30),
  cleanup_audit_days INTEGER NOT NULL DEFAULT 400 CHECK (cleanup_audit_days >= 90),
  cron_history_days INTEGER NOT NULL DEFAULT 30 CHECK (cron_history_days >= 7),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO data_retention_settings (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS data_retention_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  dry_run BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'completed', 'failed')),
  deleted_counts JSONB NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE data_retention_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE data_retention_runs ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS data_retention_runs_started_idx
  ON data_retention_runs (started_at DESC);

CREATE INDEX IF NOT EXISTS bank_sync_jobs_retention_idx
  ON bank_sync_jobs (status, requested_at)
  WHERE status IN ('done', 'failed');

CREATE INDEX IF NOT EXISTS bank_sync_jobs_connection_idx
  ON bank_sync_jobs (connection_id);

CREATE INDEX IF NOT EXISTS notifications_retention_idx
  ON notifications (is_read, created_at);

CREATE INDEX IF NOT EXISTS system_logs_retention_idx
  ON system_logs (level, created_at);

CREATE OR REPLACE FUNCTION preview_data_retention()
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH settings AS (
    SELECT * FROM data_retention_settings WHERE id = 1
  ), counts AS (
    SELECT
      (SELECT count(*) FROM password_reset_tokens
        WHERE expires_at < now() OR used = true) AS password_reset_tokens,
      (SELECT count(*) FROM email_verification_tokens
        WHERE expires_at < now() OR used = true) AS email_verification_tokens,
      (SELECT count(*) FROM agent_pairing_codes
        WHERE expires_at < now()) AS agent_pairing_codes,
      (SELECT count(*)
         FROM bank_sync_jobs j, settings s
        WHERE (
          (j.status = 'done' AND j.requested_at < now() - make_interval(days => s.sync_jobs_done_days))
          OR
          (j.status = 'failed' AND j.requested_at < now() - make_interval(days => s.sync_jobs_failed_days))
        )
          -- Preserve the newest diagnostic record for every connection.
          AND j.id <> (
            SELECT max(latest.id)
            FROM bank_sync_jobs latest
            WHERE latest.connection_id = j.connection_id
          )) AS bank_sync_jobs,
      (SELECT count(*)
         FROM notifications n, settings s
        WHERE (n.is_read AND n.created_at < now() - make_interval(days => s.read_notifications_days))
           OR (NOT n.is_read AND n.created_at < now() - make_interval(days => s.unread_notifications_days))) AS notifications,
      (SELECT count(*)
         FROM system_logs l, settings s
        WHERE (upper(l.level) = 'ERROR' AND l.created_at < now() - make_interval(days => s.error_logs_days))
           OR (upper(l.level) <> 'ERROR' AND l.created_at < now() - make_interval(days => s.system_logs_days))) AS system_logs,
      (SELECT count(*)
         FROM admin_activity_log a, settings s
        WHERE a.created_at < now() - make_interval(days => s.admin_audit_days)) AS admin_activity_log,
      (SELECT count(*)
         FROM shopping_invitations i, settings s
        WHERE (i.status = 'pending' AND i.expires_at < now())
           OR (i.status <> 'pending'
               AND coalesce(i.responded_at, i.created_at) < now() - make_interval(days => s.shopping_invitations_days))) AS shopping_invitations,
      (SELECT count(*)
         FROM agent_devices d, settings s
        WHERE d.status = 'revoked'
          AND coalesce(d.last_seen_at, d.created_at) < now() - make_interval(days => s.revoked_devices_days)) AS revoked_agent_devices,
      (SELECT count(*)
         FROM data_retention_runs r, settings s
        WHERE r.started_at < now() - make_interval(days => s.cleanup_audit_days)) AS retention_run_history,
      (SELECT count(*)
         FROM cron.job_run_details h, cron.job j, settings s
        WHERE h.jobid = j.jobid
          AND j.jobname = 'spendwise-data-retention'
          AND h.end_time < now() - make_interval(days => s.cron_history_days)) AS cron_run_history
  )
  SELECT jsonb_build_object(
    'checked_at', now(),
    'dry_run', true,
    'retention_days', jsonb_build_object(
      'sync_jobs_done', s.sync_jobs_done_days,
      'sync_jobs_failed', s.sync_jobs_failed_days,
      'read_notifications', s.read_notifications_days,
      'unread_notifications', s.unread_notifications_days,
      'system_logs', s.system_logs_days,
      'error_logs', s.error_logs_days,
      'admin_audit', s.admin_audit_days,
      'shopping_invitations', s.shopping_invitations_days,
      'revoked_devices', s.revoked_devices_days,
      'cleanup_audit', s.cleanup_audit_days,
      'cron_history', s.cron_history_days
    ),
    'eligible', to_jsonb(c),
    'total_eligible',
      c.password_reset_tokens + c.email_verification_tokens +
      c.agent_pairing_codes + c.bank_sync_jobs + c.notifications +
      c.system_logs + c.admin_activity_log + c.shopping_invitations +
      c.revoked_agent_devices + c.retention_run_history + c.cron_run_history
  )
  FROM settings s
  CROSS JOIN counts c;
$$;

CREATE OR REPLACE FUNCTION run_data_retention(p_dry_run BOOLEAN DEFAULT true)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  s data_retention_settings%ROWTYPE;
  v_run_id BIGINT;
  v_password_tokens INTEGER := 0;
  v_email_tokens INTEGER := 0;
  v_pairing_codes INTEGER := 0;
  v_sync_jobs INTEGER := 0;
  v_notifications INTEGER := 0;
  v_system_logs INTEGER := 0;
  v_admin_logs INTEGER := 0;
  v_invitations INTEGER := 0;
  v_devices INTEGER := 0;
  v_retention_history INTEGER := 0;
  v_cron_history INTEGER := 0;
  v_counts JSONB;
BEGIN
  IF p_dry_run THEN
    RETURN preview_data_retention();
  END IF;

  IF NOT pg_try_advisory_xact_lock(hashtextextended('spendwise-data-retention', 0)) THEN
    RETURN jsonb_build_object('status', 'skipped', 'reason', 'cleanup_already_running');
  END IF;

  SELECT * INTO STRICT s FROM data_retention_settings WHERE id = 1;

  INSERT INTO data_retention_runs (dry_run, status)
  VALUES (false, 'running')
  RETURNING id INTO v_run_id;

  DELETE FROM password_reset_tokens
   WHERE expires_at < now() OR used = true;
  GET DIAGNOSTICS v_password_tokens = ROW_COUNT;

  DELETE FROM email_verification_tokens
   WHERE expires_at < now() OR used = true;
  GET DIAGNOSTICS v_email_tokens = ROW_COUNT;

  DELETE FROM agent_pairing_codes
   WHERE expires_at < now();
  GET DIAGNOSTICS v_pairing_codes = ROW_COUNT;

  DELETE FROM bank_sync_jobs j
   WHERE (
     (j.status = 'done' AND j.requested_at < now() - make_interval(days => s.sync_jobs_done_days))
     OR
     (j.status = 'failed' AND j.requested_at < now() - make_interval(days => s.sync_jobs_failed_days))
   )
     AND j.id <> (
       SELECT max(latest.id)
       FROM bank_sync_jobs latest
       WHERE latest.connection_id = j.connection_id
     );
  GET DIAGNOSTICS v_sync_jobs = ROW_COUNT;

  DELETE FROM notifications n
   WHERE (n.is_read AND n.created_at < now() - make_interval(days => s.read_notifications_days))
      OR (NOT n.is_read AND n.created_at < now() - make_interval(days => s.unread_notifications_days));
  GET DIAGNOSTICS v_notifications = ROW_COUNT;

  DELETE FROM system_logs l
   WHERE (upper(l.level) = 'ERROR' AND l.created_at < now() - make_interval(days => s.error_logs_days))
      OR (upper(l.level) <> 'ERROR' AND l.created_at < now() - make_interval(days => s.system_logs_days));
  GET DIAGNOSTICS v_system_logs = ROW_COUNT;

  DELETE FROM admin_activity_log a
   WHERE a.created_at < now() - make_interval(days => s.admin_audit_days);
  GET DIAGNOSTICS v_admin_logs = ROW_COUNT;

  DELETE FROM shopping_invitations i
   WHERE (i.status = 'pending' AND i.expires_at < now())
      OR (i.status <> 'pending'
          AND coalesce(i.responded_at, i.created_at) < now() - make_interval(days => s.shopping_invitations_days));
  GET DIAGNOSTICS v_invitations = ROW_COUNT;

  DELETE FROM agent_devices d
   WHERE d.status = 'revoked'
     AND coalesce(d.last_seen_at, d.created_at) < now() - make_interval(days => s.revoked_devices_days);
  GET DIAGNOSTICS v_devices = ROW_COUNT;

  DELETE FROM data_retention_runs r
   WHERE r.id <> v_run_id
     AND r.started_at < now() - make_interval(days => s.cleanup_audit_days);
  GET DIAGNOSTICS v_retention_history = ROW_COUNT;

  DELETE FROM cron.job_run_details h
   USING cron.job j
   WHERE h.jobid = j.jobid
     AND j.jobname = 'spendwise-data-retention'
     AND h.end_time < now() - make_interval(days => s.cron_history_days);
  GET DIAGNOSTICS v_cron_history = ROW_COUNT;

  v_counts := jsonb_build_object(
    'password_reset_tokens', v_password_tokens,
    'email_verification_tokens', v_email_tokens,
    'agent_pairing_codes', v_pairing_codes,
    'bank_sync_jobs', v_sync_jobs,
    'notifications', v_notifications,
    'system_logs', v_system_logs,
    'admin_activity_log', v_admin_logs,
    'shopping_invitations', v_invitations,
    'revoked_agent_devices', v_devices,
    'retention_run_history', v_retention_history,
    'cron_run_history', v_cron_history
  );

  UPDATE data_retention_runs
     SET finished_at = now(), status = 'completed', deleted_counts = v_counts
   WHERE id = v_run_id;

  RETURN jsonb_build_object(
    'status', 'completed',
    'run_id', v_run_id,
    'deleted', v_counts,
    'total_deleted',
      v_password_tokens + v_email_tokens + v_pairing_codes + v_sync_jobs +
      v_notifications + v_system_logs + v_admin_logs + v_invitations +
      v_devices + v_retention_history + v_cron_history
  );
END;
$$;

REVOKE ALL ON TABLE data_retention_settings FROM anon, authenticated;
REVOKE ALL ON TABLE data_retention_runs FROM anon, authenticated;
REVOKE ALL ON FUNCTION preview_data_retention() FROM PUBLIC;
REVOKE ALL ON FUNCTION run_data_retention(BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION preview_data_retention() TO service_role;
GRANT EXECUTE ON FUNCTION run_data_retention(BOOLEAN) TO service_role;

COMMENT ON TABLE data_retention_settings IS
  'Single-row, conservative retention policy for operational data only.';
COMMENT ON TABLE data_retention_runs IS
  'Bounded audit history for automatic retention cleanup runs.';
COMMENT ON FUNCTION preview_data_retention() IS
  'Read-only report of rows eligible for operational-data cleanup.';
COMMENT ON FUNCTION run_data_retention(BOOLEAN) IS
  'Deletes expired/old operational rows; defaults to a non-destructive dry run.';

-- 02:20 UTC daily (04:20 Israel winter / 05:20 Israel summer).
-- Reusing the same job name updates the schedule instead of duplicating it.
SELECT cron.schedule(
  'spendwise-data-retention',
  '20 2 * * *',
  'SELECT public.run_data_retention(false);'
);
