-- Calendar-month accounting foundation. Ledger facts remain unchanged.

CREATE TABLE IF NOT EXISTS salary_signatures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bank_source TEXT NOT NULL,
  bank_account_number TEXT,
  normalized_description TEXT NOT NULL,
  display_description TEXT NOT NULL,
  month_offset SMALLINT NOT NULL DEFAULT -1 CHECK (month_offset BETWEEN -2 AND 0),
  active BOOLEAN NOT NULL DEFAULT true,
  created_from_transaction_id INTEGER REFERENCES transactions(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS salary_signatures_active_unique
  ON salary_signatures (
    user_id,
    bank_source,
    COALESCE(bank_account_number, ''),
    normalized_description
  ) WHERE active = true;

CREATE INDEX IF NOT EXISTS salary_signatures_user_idx
  ON salary_signatures (user_id) WHERE active = true;

CREATE TABLE IF NOT EXISTS transaction_month_overrides (
  transaction_id INTEGER PRIMARY KEY REFERENCES transactions(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  economic_month DATE NOT NULL CHECK (EXTRACT(DAY FROM economic_month) = 1),
  classification TEXT NOT NULL CHECK (classification IN (
    'salary', 'bonus', 'financing', 'transfer', 'card_settlement', 'other'
  )),
  reason TEXT,
  created_by TEXT NOT NULL DEFAULT 'user' CHECK (created_by IN ('user', 'system_review')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS transaction_month_overrides_user_month_idx
  ON transaction_month_overrides (user_id, economic_month);

ALTER TABLE salary_signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_month_overrides ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON salary_signatures FROM anon, authenticated;
REVOKE ALL ON transaction_month_overrides FROM anon, authenticated;

COMMENT ON TABLE salary_signatures IS
  'User-confirmed salary identity; matched salary is attributed to a calendar work month.';
COMMENT ON TABLE transaction_month_overrides IS
  'Auditable exceptions to derived calendar-month attribution; never changes ledger dates.';

